name: Test

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test.yaml'
      - '.github/workflows/push-docker.yaml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test.yaml'
      - '.github/workflows/push-docker.yaml'
  workflow_dispatch:

jobs:
  test_program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Go and swagger docs
        uses: ./.github/actions/setup-go-swagger
        with:
          go-version: '1.25'
          install-ffmpeg: 'true'

      - name: Run tests
        uses: robherley/go-test-action@v0
        env:
          ANONYMOUS_LOGIN: true
        with:
          testArguments: './... -timeout 2h'
          omit: successful
